CREATE USER KFA IDENTIFIED BY bmw325xi;

--ALTER USER KFA IDENTIFIED BY bmw325xi;

GRANT CONNECT, CREATE SESSION, RESOURCE TO KFA; 
GRANT CREATE SESSION TO KFA;

ALTER USER KFA quota unlimited on USERS;

SELECT * FROM dba_sys_privs WHERE GRANTEE = 'KFA'; 
SELECT * FROM dba_tab_privs WHERE GRANTEE = 'KFA'; 
SELECT * FROM dba_role_privs WHERE GRANTEE = 'KFA';

SELECT * FROM ALL_USERS 

SELECT * FROM user_sys_privs;

SELECT * FROM dba_sys_privs WHERE grantee = 'kfa';

/*CREATE schema AUTHorization KFA
	CREATE TABLE Cell_Number
	(id NUMBER PRIMARY KEY, Cell_number varchar2(12))
	GRANT ALL ON cell_number TO system;*/

CREATE OR REPLACE DIRECTORY InputDir AS 'D:\OraInputDir'

GRANT READ, WRITE ON Directory InputDir TO KFA;
 
/*
CREATE TABLE ext_Cell_Number
(
CellNumber VARCHAR2(12)
)
ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY InputDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
BADFILE 'ext_Cell_Number.bad'
LOGFILE 'ext_Cell_Number.log'
DISCARDFILE 'ext_Cell_Number.dis'
--SKIP 1
STRINGs
(
CellNumber CHAR(12)
)
FIELDS TERMINATED BY ','
)
LOCATION ('CellNumbers.csv')
)
REJECT LIMIT UNLIMITED;
*/
--GRANT SELECT ON ext_Cell_Number TO KFA;

SELECT --OWNER, DIRECTORY_NAME, DIRECTORY_PATH, SECONDARY_PATH
* 
FROM DBA_DIRECTORIES ORDER BY DIRECTORY_NAME;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));


SELECT * FROM v$sql